### ISSUE TITLE
SarimaTradingDaysTest hyperParametersCount with mean 

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#108]
Since the `arima.getParametersCount()` do not consider if the intercept is included i was wondering if the hyperParametersCount() should be increased by 1 when `mean = true` ?
https://github.com/jdemetra/jdplus-main/blob/7aeb4a7fa15225af4f1371fe48fde49faf28ce7a/jdplus-main-base/jdplus-toolkit-base-parent/jdplus-toolkit-base-core/src/main/java/jdplus/toolkit/base/core/regsarima/ami/SarimaTradingDaysTest.java#L52

**Comment by AQLT** [comment]
Maybe `arima.getParametersCount()` should be replaced by `regarima.getVariablesCount()`because it also don't take into account the regressors variables. I think the hyperparameters should also be modified in `TradingDaysTest.java`:
https://github.com/jdemetra/jdplus-main/blob/7aeb4a7fa15225af4f1371fe48fde49faf28ce7a/jdplus-main-base/jdplus-toolkit-base-parent/jdplus-toolkit-base-core/src/main/java/jdplus/toolkit/base/core/modelling/regular/tests/TradingDaysTest.java#L110
It would also explain why we cannot reproduce the residual trading tests in R (https://github.com/rjdemetra/rjd3x13/issues/13).

**Comment by palatej** [comment]
Hi Alain, 

You can see in the Java code of the class JointTest (https://github.com/jdemetra/jdplus-main/blob/develop/jdplus-main-base/jdplus-toolkit-base-parent/jdplus-toolkit-base-core/src/main/java/jdplus/toolkit/base/core/stats/linearmodel/JointTest.java) that we take into account the number of regression variables (include the trend mean) for computing the degrees of freedom. So, I think that the code is correct.

**Comment by AQLT** [comment]
Hi Jean,
Thank you for your answer. You are surely right for SarimaTradingDaysTest.java, the problem seems to come from elsewhere I will open an issue in rjd3toolkit.
For TradingDaysTest.java there still are some differences with the results of `rjd3toolkit::td_f()` function (e.g. with the degree of freedom), is it intentional?
``` r
library(rJava)
library(rjd3toolkit)
y <- ABS$X0.2.09.10.M
tdtest <- J("jdplus.toolkit.base.core.modelling.regular.tests.TradingDaysTest")
testjd <- rjd3toolkit:::.jd2r_test(tdtest$maTest(rjd3toolkit:::.r2jd_tsdata(y), FALSE))
test_rjd3 <- td_f(y, "R011")
attr(testjd, "distribution")
#> [1] "F with 6.0 degrees of freedom in the nominator and 418.0 degrees of freedom in the denominator"
attr(test_rjd3, "distribution")
#> [1] "F with 6.0 degrees of freedom in the nominator and 417.0 degrees of freedom in the denominator"

testjd <- rjd3toolkit:::.jd2r_test(tdtest$maTest(rjd3toolkit:::.r2jd_tsdata(y), TRUE))
test_rjd3 <- td_f(y, "AIRLINE")
attr(testjd, "distribution")
#> [1] "F with 6.0 degrees of freedom in the nominator and 406.0 degrees of freedom in the denominator"
attr(test_rjd3, "distribution")
#> [1] "F with 6.0 degrees of freedom in the nominator and 404.0 degrees of freedom in the denominator"
```

**Comment by palatej** [comment]
Ok. I see the difference: in td_f, I correct the df for the number of parameters in the model (Tramo-like) and in the other case, I don't correct (X12-like). I will use the same approach (tramo-like) to get the same results.
