### ISSUE TITLE
decimal separator in Txt files

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#155]
It could be good to be able to change the decimal separator for the imported txt files. Depending on your system (if the decimal separator is the comma), you cannot for example import a csv exported by JDemetra+.

**Comment by charphi** [comment]
I need some more information. Are you talking about the desktop application or the command-line tool?

**Comment by AQLT** [comment]
I'm talking about the desktop application. When I go to `Providers > Txt files >  Open` we cannot change the decimal separator (same as in the previous versions). However I would find it useful to be able to do this. Using a French computer, when I export data from JDemetra+ the decimal separator used is the comma. To import it again in the desktop application I have to modify the csv file by hand.

**Comment by charphi** [comment]
In fact, you can change the decimal separator by selecting the corresponding locale:
![2023-11-15 10_21_27-JDemetra+ 3 1 1](https://github.com/jdemetra/jdplus-main/assets/8778378/6b4f9358-88a3-41eb-840c-ac0ecc3f95d9)

**Comment by AQLT** [comment]
Awesome! I didn't know this setting was for that. Thanks!
