### ISSUE TITLE
Default date format of JDemetra+ outputs

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#156]
I think it would be good if the default date format of JDemetra+ outputs were the same as the default import format (yyyy-MM-dd).

**Comment by charphi** [comment]
Are you referring to batch output or series "Save to" feature ?

**Comment by AQLT** [comment]
I'm referring to the export functionality of a multi-document. When I select `csv` and presentation `VTable` the dates are in the format `2002-01-01T00:00:00/P1M`. I've just noticed that when I select `Htable` they are in the format `2002-01-01`.

**Comment by charphi** [comment]
This looks like a bug. I'm going to check...

**Comment by charphi** [comment]
Fixed in 82b0ac452f06e25c46b0d674b3bee0e48a8b43d3
