### ISSUE TITLE
FinalSeasonalFilter in X11ResultsProto

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#195]
Why the final seasonal filter is not included in `X11ResultsProto` ?
https://github.com/jdemetra/jdplus-main/blob/develop/jdplus-main-base/jdplus-x13-base-parent/jdplus-x13-base-protobuf/src/main/java/jdplus/x13/base/protobuf/X11ResultsProto.java#L70
It would solve https://github.com/rjdemetra/rjd3x13/issues/4.

**Comment by palatej** [comment]
Added in 3.2.2
