### ISSUE TITLE
'Configure...' context menu option not working

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#215]
When I right-click on a chart and select 'Configure...' from the context menu, nothing seems to happen:

![screenshot](https://github.com/jdemetra/jdplus-main/assets/110582146/7984b7f6-a2be-4725-b28d-1e53949217df)

**Comment by charphi** [comment]
Fixed in 1a7a9c05947687ab2197afb5be62d36210c4d0c7
