### ISSUE TITLE
Fix encoding of space characters in URI

### ISSUE THREAD

**Issue by charphi** [jdemetra/jdplus-main#254]
Current implementation of URI formatting in `DataSource` and `DataSet` encodes space characters as `+` instead of `%20`.
This comes from backward compatibility in Java [`URLEncoder`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URLEncoder.html).

More info: 
- https://www.baeldung.com/java-urlencoder-translate-space-characters
- https://guava.dev/releases/23.0/api/docs/com/google/common/net/UrlEscapers.html
- https://stackoverflow.com/questions/2678551/when-should-space-be-encoded-to-plus-or-20
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/UriBuilder.html
- https://hc.apache.org/httpcomponents-core-5.2.x/current/httpcore5/apidocs/org/apache/hc/core5/net/URIBuilder.html

**Comment by TanguyBarthelemy** [comment]
Is this resolved? I just tested the SNAPSHOT of the v3.2.3 and I still get some `+` in the path:
![image](https://github.com/jdemetra/jdplus-main/assets/112711017/d7325b7f-8fe9-4be4-bc82-40c6911647c0)

**Comment by charphi** [comment]
I don't have the problem. Try do create a new workspace from scratch. Maybe it is just old URI from previous version.

**Comment by TanguyBarthelemy** [comment]
I downloaded the latest snapshot from this morning and now it works!
Maybe I tested with a too old snapshot...
