### ISSUE TITLE
Moving plot windows in Main results

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#262]
Is there a way to move the Main results curve windows above each other (as indicated by the diagram):

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/0422b483-6238-4090-98e7-84d5d84e18bc)

Here's a preview of what it might look like:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/58e7d77d-a738-4d91-844a-a74a3f90f67f)

**Comment by charphi** [comment]
Done in https://github.com/jdemetra/jdplus-main/pull/375
