### ISSUE TITLE
Import data: rename frequency to aggregation frequency

### ISSUE THREAD

**Issue by annasmyk** [jdemetra/jdplus-main#271]
rename frequency to aggregation frequency in data import wizard 
otherwise very confusing

![image](https://github.com/jdemetra/jdplus-main/assets/43274870/182df1da-d373-4e08-a3d0-17261936b511)

**Comment by TanguyBarthelemy** [comment]
Indeed you can import a quaterly time series and choose to import it as a monthly series.

My file:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/fca9c5d1-5078-45ff-b42b-e1f10920fe54)

Choose frequency monthly:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/952bd4e1-fbf5-4448-b3aa-c74b0af799fb)

The date appears as monthly data:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/8f6aa671-952b-4297-a01b-3716e8d34da5)

**Comment by charphi** [comment]
@annasmyk @TanguyBarthelemy 

> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

What about ...
- Expected Frequency
- Forced Frequency
- Intended Frequency
- Unified Frequency

**Comment by palatej** [comment]
I prefer forced frequency
