### ISSUE TITLE
Drag and drop multi-processing

### ISSUE THREAD

**Issue by clemasso** [jdemetra/jdplus-main#288]
Compared with v2, a quick drag and drop of the data no longer succeeds with multi-processing (‘Statistical methods’ - ‘Seasonal Adjustment’ - ‘Multi Processing’ - ‘New’). 

![image](https://github.com/jdemetra/jdplus-main/assets/95612140/acfcda89-5098-40cf-b45b-8d1f1ed357f3)

**Comment by TanguyBarthelemy** [comment]
Hi Corentin, 

You need to first select a specification:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/e34faf05-a083-4aa3-8816-2b12a919ea6e)

Then you can drop your series:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/edb2d697-9d52-40e2-b57d-b3f46eb8b9f9)

But compared with v2, even if you have selected a specification, you **can't drop** series from a grid to a SA-Processing:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/a6238d18-6fc2-49d3-8d4b-190aafb315af)

Also, you can select a specification by default in `Tools` --> `Options`:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/e6037161-07fb-4182-88a2-e6dabc001b13)

Then `SA` --> `Seasonal Adjustment` --> `Default method` then you can choose your default specification( TramoSeats or X13):

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/4d0a8272-fb31-44b6-97f3-443ad51ff117)

So you can now drop your data (from `Providers`) to a SA-Processing without specifying a specification each time.

**Comment by TanguyBarthelemy** [comment]
I agree too. It can be misleading for the user not to have to define a spec and receive TramoSeats by default...
For me the issue can be closed.
