### ISSUE TITLE
add benchmarking.results in the content of batch output

### ISSUE THREAD

**Issue by clemasso** [jdemetra/jdplus-main#289]
Would it be possible to add the output benchmarking.result (i.e. SA series after benchmarking) to the content list of the results we can export via Batch output? This was there in v2 (see snapshot) but not yet in v3.

![image](https://github.com/jdemetra/jdplus-main/assets/95612140/c299449f-454f-4abe-9e4f-432b162f32d2)

**Comment by charphi** [comment]
Same as https://github.com/jdemetra/jdplus-main/issues/179 ?

**Comment by palatej** [comment]
Solved in #324
