### ISSUE TITLE
Description field is missing

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#291]
Comparing v2.2.4 and v3.2.2, with the same variables, the `Description` field is missing when creating variables in a workspace:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/8d58f810-23b0-48c8-9025-a13d761d13eb)

Is it possible to add this field, based on the series name (from the file) as in v2 ?

**Comment by charphi** [comment]
Add a contextual menu to copy description column to name column

**Comment by charphi** [comment]
![Screenshot 2024-06-07 140312](https://github.com/jdemetra/jdplus-main/assets/8778378/74fcb051-646d-427f-9905-32b03e1b7a63)
