### ISSUE TITLE
GUI Excel output with version v3.2.2

### ISSUE THREAD

**Issue by veroniqueelter** [jdemetra/jdplus-main#303]
Dear all, 

I still have problems to create an Excel output with the GUI of the newest version of JDemetra+ (v3.2.2). 
I always get the following error message: 

Can't generate output (Excel)
java.io.IOException: Cannot find spreadsheet writer for file 'C:\Test_JDemetra_plus\Test_JDemetra_3.2.2\CLV_1_AfterFirstBreak\CUP_1_BeforeFirstBreak'

Our IT team thinks that the issue comes from JDemetra+. What could be the reason behind this and what can I do to solve the problem? 
Thank you very much in advance for your help, 
Best greetings, 
Véronique

**Comment by TanguyBarthelemy** [comment]
We discussed yesterday about your issue with @charphi .
The error is saying that your file doesn't end with a file extension (for example `.xls`, `.xlsx` or `.ods`).

Please try to change your file extension (by hand or with Excel for example) to update your filename.

**Comment by veroniqueelter** [comment]
I just tried it out and it works perfectly well now. The problem was that the file extension never needed to be mentioned in the older versions. I will take note of it. With this issue fixed, the new version is ready for production for us. Thank you very much.

**Comment by TanguyBarthelemy** [comment]
Good to know!

**Comment by veroniqueelter** [comment]
Just another question: is it planned to switch the Date format in the Excel output back to "General" or will it be kept in the new "Date" Format? just to know if I need to adapt my subsequent macros or not, as it used to be in the "General" format. Thank you very much in advance. Véronique

**Comment by charphi** [comment]
For the Excel output, you have to explicitly specify the file extension so that the program knows which file format you want to use. This is indeed a behavior change from the v2. I'm thinking about two solution for that problem:
- automatically add default file extension (implicit solution)
- add a combobox with file format (explicit solution)

**Comment by charphi** [comment]
> Just another question: is it planned to switch the Date format in the Excel output back to "General" or will it be kept in the new "Date" Format? just to know if I need to adapt my subsequent macros or not, as it used to be in the "General" format. Thank you very much in advance. Véronique

The new "Date" format is just the Excel date cell type without formatting.
I don't know how your macros work but as a cell type, it should be fine. As a string value, that will be indeed anoying.
I'm not planning to change the behavior for the time being.

**Comment by charphi** [comment]
I've chosen the implicit solution: automatically add default file extension
