### ISSUE TITLE
Can't read `.ods` file

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#309]
On this issue (jdemetra/jdemetra-app#881) I got an issue while importing `.ods` files with V2 and V3 (https://github.com/jdemetra/jdemetra-app/issues/881#issuecomment-2115573274)

Is it resolved in V3?

**Comment by charphi** [comment]
It is the same problem in v3 since v2 and v3 use the same library.
It will be solved in the next release of v3.

**Comment by TanguyBarthelemy** [comment]
I just tested the latest snapshot. 
It's resolved, thanks!
_(I shouldn't have reopened an issue, but I had a cold sweat)._

**Comment by charphi** [comment]
Not a problem; I will use this issue in the release notes

**Comment by charphi** [comment]
Done in 795efa71ad87dd845b19c420499557af09b1f180
