### ISSUE TITLE
Seasonal component undefined in HF SA

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#336]
When I try to adjust (SA) a HF series and I plot the different seasonal patterns, I get the same legend for the different periodicity:

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/c340cc62-69ed-42ba-ac85-5244b24fcba3)

Is it possible to add an information about:

- the periodicity used (annual, weekly, daily...)
- or with the value of the periodicity (p = 365.2425, p = 7, p = 31...)

to differentiate the two components?

Thank you!

**Comment by palatej** [comment]
Should be moved to incubator

**Comment by palatej** [comment]
Solved in incubator v2.2.1

**Comment by TanguyBarthelemy** [comment]
Thank you @palatej! I will test it as soon as it will be released.
