### ISSUE TITLE
Strange bug affecting start date and other parameters

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#368]
The following describes a bug in JDemetra+ version 3.2.2 that is reproducible under certain scenarios but exhibits inconsistency in others.

Consider the following spreadsheet of random time series data: [random_data.xlsx](https://github.com/user-attachments/files/16104095/random_data.xlsx). There are two monthly series it contains:
- ‘Series_start_Sep2017’ is a time series of random integers (see the spreadsheet formulae for details) ranging from **September 2017** to December 2023; and
- ‘Series_start_Apr2017’ is the same series, but with additional random data (see the spreadsheet formulae for details) at the start, and ranges from **April 2017** to December 2023.

Perform the following steps to reproduce the bug:
1. Load the spreadsheet into JD+.
2. Create an X13 single-analysis document for each of the two series above.
3. Accept all default JD+ settings (spec: RSA4) but apply the following changes in the Specifications panel:
    i. Under SERIES, uncheck ‘Preliminary Check’.
    ii. Under TRANSFORMATION, set ‘function’ to ‘Log’.
    iii. Under REGRESSION, disable trading day and Easter.
    iv. Under OUTLIERS, uncheck ‘Is enabled’.
    v. Under X11, set ‘Mode’ to ‘Multiplicative’, set ‘Seasonal filter’ to ‘S3X5’, uncheck ‘Automatic Henderson filter’, and check ‘Excludeforecast’.
4. Click ‘Apply’ once the changes are made in the Specifications panel.

These two JD+ series thus have the same data and specifications except for additional data in the periods from April 2017 to August 2017 for the series ‘Series_start_Apr2017’. See the following workspace files: [bug_workspace.zip](https://github.com/user-attachments/files/16104112/bug_workspace.zip):
- X13Doc-1 corresponds to the series ‘Series_start_Apr2017'
- X13Doc-2 corresponds to the series ‘Series_start_Sep2017'

Observe the following:
- For the series ‘Series_start_Apr2017’, X13 output is produced, indicating a successful run without errors. 
- For the series ‘Series_start_Sep2017’, the X13 output is blank, indicating an error has occurred. (As an aside, please note the importance of surfacing errors to the user as raised in: #283.)

Now try the following:
- For both series, uncheck ‘Excldudeforecast’ in the Specifications panel, and apply the changes.
    - Observe that the series ‘Series_start_Sep2017’ now runs successfully.
- For both series, change the underlying spreadsheet data (that is, generate new random data).
    - Observe that the outcome is the same: the series ‘Series_start_Apr2017’ remains successful, but the series ‘Series_start_Sep2017’ remains unsuccessful.
    - This seems to suggest that the series’ original data values are themselves not the cause of the bug.

**Why does the different starting date prevent the series ‘Series_start_Sep2017’ from running successfully?
Why does including forecasts (that is, unchecking ‘Excludeforecast’) solve the issue?**

We can reproduce the bug similarly in the Cruncher, suggesting the bug is in the core JDemetra+ libraries. Specifically, if the series demonstrating this bug is run through the Cruncher, it produces no output aside from a demetra_m.csv file. That file contains nothing but the name of the series. 

We also experimented with other series. Some series ran successfully only when the start period was anything but August, September, October or November. For other series, even with 'ExcludeForecast' set as true, these months were not an issue. This suggests the issue may be related to the original data values, contrary to what is mentioned above, or to some other combination of parameters. We also experimented with changing the length of the series; doing so does not appear to be related to the issue.

**Comment by Immurb** [comment]
Thanks for this very helpful description of this problem.
It seems to be an edge case in the calculation of the standard deviation in the B4 step that goes out of bound. We will test our solution and then push a fix.
