### ISSUE TITLE
What is the 'period' value for a seasonal outlier (SO)?

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#414]
When inserting a seasonal outlier (SO), the XML file contains a 'period' tag:

![image](https://github.com/user-attachments/assets/684d1785-a1a1-4924-9325-d26a1b9d3e20)

I've tried searching the R and netlify documentation (e.g. https://jdemetra-new-documentation.netlify.app/a-sa-pre-treatment#outliers), but I can't find anything to explain it. What does it mean, and can it be changed by the user, or does JD+ estimate it on behalf of the user?

**Comment by palatej** [comment]
The period is the length of a cycle (= number of obs to retrieve the same pattern). Usually, it is the annual frequency, but it could be something else in high frequency series (for example 7  for a weekly SO in daily series). 
Technically speaking, the SO is defined by   ... 0 1 0 ... 0 1  0 ... 0 1 0 0 0 0 0 and the 1 are separated by (p-1) 0
