### ISSUE TITLE
x11.mode option has disappeared?

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#462]
I do not see anymore the X11.mode option since 3.2.4: is it somewhere else?

**Comment by palatej** [comment]
X11.mode only appear when you have several choices:
- log transformation -> multiplicative or log-additive
- no pre-adjustment

In all the other cases, it is automatically derived from the transformation (fn=auto) or it can't be modified (fn=add)

**Comment by AQLT** [comment]
Thanks @palatej. Then it means that we cannot anymore do a log-additive or pseudo-additive decomposition with pre-processing?

**Comment by palatej** [comment]
You can do a log-additive decomposition with pre-processing when logs have been chosen (choice between multiplicative or log-additive).
For the pseudo-additive decomposition, you can't indeed use pre-processing.
