### ISSUE TITLE
X11 mode options in GUI

### ISSUE THREAD

**Issue by MichelleHedger** [jdemetra/jdplus-main#478]
The x11.mode options menu is only available in the GUI when regarima.transform.function = Log.
In this case, the x11.mode option is between Multiplicative and LogAdditive.
![image](https://github.com/user-attachments/assets/ed08948d-ea65-4f14-b912-99cb3ff9ca05)

If regarima.transform.function = None, there is no x11.mode option box.
![image](https://github.com/user-attachments/assets/6caff14b-1fcc-43fe-b667-510f6c9a3b8e)

If regarima.transform.function = Auto, there is also no x11.mode option box.
![image](https://github.com/user-attachments/assets/0fde1fc5-fcbd-48a9-b3c4-d2987eb0c56a)

From the code for DecompositionMode, it appears that the options for x11.mode should be {Undefined, Additive, Multiplicative, LogAdditive and PseudoAdditive}. I understand that some of these are only appropriate under certain transformations, however, I am unsure how to set x11.mode to Additive or PseudoAdditive using the GUI.

**Comment by Immurb** [comment]
AQLT had the same question in #462
To quote Jean:

> X11.mode only appear when you have several choices:
> 
> log transformation -> multiplicative or log-additive
> no pre-adjustment
> In all the other cases, it is automatically derived from the transformation (fn=auto) or it can't be modified (fn=add)

> You can do a log-additive decomposition with pre-processing when logs have been chosen (choice between multiplicative or log-additive).
For the pseudo-additive decomposition, you can't indeed use pre-processing.
