### ISSUE TITLE
Locating initial and final unit root options in GUI

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#480]
Regarding the entries for 'Initial UR (Diff.)' and 'Final UR (Diff.)' at: https://jdemetradocumentation.github.io/JDemetra-documentation/pages/reference-manual/modelling-spec-arima.html

![image](https://github.com/user-attachments/assets/085b7c7c-97c7-4d20-b863-847c0184fd8c)

...where can they be found in the JD+ GUI? The only options available seem to be the following:

![image](https://github.com/user-attachments/assets/eef045ec-7f1d-48be-9eb4-f542c8f1a933)

Similarly, how can a user set the following related options?

![image](https://github.com/user-attachments/assets/2b5264ca-0185-4d8e-93e4-c4cde3db1047)

Note that 'hrinitial' is not explained at: https://jdemetradocumentation.github.io/JDemetra-documentation/pages/reference-manual/modelling-spec-arima.html

See also: https://github.com/jdemetra/jdplus-main/issues/479

**Comment by Immurb** [comment]
Under Options -> Demetra -> Behaviour there is the option "Show low-level options", if it is checked all parameters that were available in version 2 should be visible.

**Comment by a-s-russo** [comment]
Thanks for explaining @Immurb.
