### ISSUE TITLE
Indirect seasonal adjustment functionality not appearing in GUI

### ISSUE THREAD

**Issue by MichelleHedger** [jdemetra/jdplus-main#486]
The documentation in https://jdemetradocumentation.github.io/JDemetra-documentation/pages/case-studies/detailedsa-direct.html says that there is a feature for comparing direct and indirect adjustment. The button for this functionality doesn't appear in the GUI for me:
![image](https://github.com/user-attachments/assets/d18757d9-cc28-4154-86c9-e980a20f6d82)

**Comment by TanguyBarthelemy** [comment]
This documentation is not up to date. Please refer to the [new documentation of JDemetra+](https://jdemetra-new-documentation.netlify.app/).

There, you can find a section on [Direct / Indirect method](https://jdemetra-new-documentation.netlify.app/t-gui-sa-modelling-features#in-gui-v2) and your information:

> This Direct-Indirect method is not implemented in v3.

So I assume you are working with JDemetra+ in version >= 3.0

**Comment by MichelleHedger** [comment]
That makes sense, thanks Tanguy!
