### ISSUE TITLE
Sigma.vector in X-11

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#65]
It seems that when Calendarsigma is set to "Select", the sigma vector cannot be changed (we can see the message `[Ljdplus.x13.base.ap...` but we cannot click) and then we cannot anymore change the calendar sigma option (message "Sigmavec mustn't be used without CalendarSigmaOption Select").

**Comment by ChristianeHofer** [comment]
Fixed in 3.2.2
