### ISSUE TITLE
Not admisible values T-Stat and Correlation of estimates matrix

### ISSUE THREAD

**Issue by maria-novas** [jdemetra/jdplus-main#78]
Hi,
we are running the following specification:
Specification

Series
Serie span: ALL
Preliminary Check: Yes

Estimate
Model span: ALL
Tolerance: 1e-07
Exact ML: No
Unit root limit: 0.96

Transformation
Function: LEVEL
AIC difference: 
Adjust: NONE

Regression
Calendar regressor: TD7
with Leap Year: No
AutoAdjust: FALSE
Test: TEST_NO

Easter: INCLUDEEASTER

Pre-specified outliers: 8
	- LS (2008-10-01) 
	- LS (2009-01-01) 
	- AO (2020-01-01) 
	- AO (2020-04-01) 
	- AO (2020-07-01) 
	- AO (2020-10-01) 
	- AO (2021-01-01) 
	- AO (2021-04-01) 
Ramps: No
User-defined variables: No

Outliers
Is enabled: No

ARIMA
SARIMA model:  (3,1,2) (1,0,1)

Coefficients
             Estimate      Type
phi(1)     1.51126240 ESTIMATED
phi(2)     0.21905144 ESTIMATED
phi(3)    -0.29221664 ESTIMATED
theta(1)   1.66167495 ESTIMATED
theta(2)   0.66200604 ESTIMATED
bphi(1)   -0.97216183 ESTIMATED
btheta(1)  0.04464834 ESTIMATED

Specification SEATS
Approximation mode: APP_LEGACY
MA unit root boundary: 0.95
Trend boundary: 0.5
Seasonal tolerance: 2
Seasonal boundary: 0.8
Method: ALG_BURMAN

Benchmarking
Is enabled: No

and the results seems to have a numerical problem as you can see in the image attached.
Thanks  in advance
![CorrelationEstimates](https://github.com/jdemetra/jdplus-main/assets/17139327/62794c6f-31f8-4771-bd61-b5b23c09a617)

**Comment by palatej** [comment]
There is indeed a numerical problem (the stdev of the parameters are based on a numerical approximation of the hessian of the likelihood; in same cases, it can degenrate)
Could you send me the data, please.
Thank you in advance

**Comment by palatej** [comment]
Ok. I see the problem. The model contains a unit root (-1) in the AR polynomial. I will add a test to avoid such a case.
Thanks !
