### ISSUE TITLE
Difference between `.builder` and `new`

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#79]
Sometimes in the Java code, new objects are created with `new` and other with the `.builder`.
For example, below the **SaItems** `items` is build with `.builder` whereas the **WorkspaceItemDescriptor** `cur` and the **Map<String, String>** `meta` are constructed with new:

https://github.com/jdemetra/jdplus-main/blob/1a19d8b2d7d91110873773f30168eacc8fdb88e1/jdplus-main-base/jdplus-sa-base-parent/jdplus-sa-base-workspace/src/main/java/jdplus/sa/base/workspace/Ws.java#L119-L132

Is there a difference in the use of this 2 constructors ?

**Comment by charphi** [comment]
These are two different-yet-related patterns.
Usually, a class has either a builder or a public constructor but not both.
Basically, you use a contructor if you have few parameters and a builder if you a a lot of parameters.

To get started with these concepts, I would recommend the following book:
https://www.oreilly.com/library/view/effective-java-3rd/9780134686097/

**Comment by TanguyBarthelemy** [comment]
Ok, thank you for the explanation!
