### ISSUE TITLE
Method naming question

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#80]
Why the methods used to set informations on a **SaItem** are named `with...` and not `set...` ?
Maybe it's a naming convention or just an arbitrary choice ?

Here the method `withSpecification`:

https://github.com/jdemetra/jdplus-main/blob/1a19d8b2d7d91110873773f30168eacc8fdb88e1/jdplus-main-base/jdplus-sa-base-parent/jdplus-sa-base-api/src/main/java/jdplus/sa/base/api/SaItem.java#L123

**Comment by charphi** [comment]
This is the "With" pattern.

`SaItem` is an immutable object. That means that its state cannot be changed once it is created.
So, to change a parameter, you need to create a new object by deriving the original one. 

More info at https://projectlombok.org/features/With

**Comment by TanguyBarthelemy** [comment]
Thank you
