### ISSUE TITLE
Different metadata format for raw data path in the XML of SAP

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#82]
Depending on the format of the data, the raw data path is not written with the same pattern in the XML files of the SAProcessing. 

For example, with XLS files, the path looks like this: 
```
"...data_ipi.xls#seriesName=RF0610&amp;sheetName=Feuil1""
```
The path to access the series is defined according to the **column name** of the series and not its placement so we can invert columns in the excel raw data file and there won't be any consequence for our workspace when refreshing.

For CSV files, the path looks like this: 
```
"...data_ipi.csv#seriesIndex=4"
```
So here the path to access the series depends only on its position in the file (its index) and not on its column name. So we can delete or change the column names, it won't change the data of the workspace during the refreshing.

I don't know which property is better than the other when working with raw data files but why these different data files are recorded differently ? Is it possible to unify the rules for writing file paths or maybe it's totally useless ?

**Comment by charphi** [comment]
XLSX files and CSV files are read by two different TS providers.
Their IDs are their own and are not necessary related.

We can argue about which method is the best but the current way is an historical one:
we try to keep the IDs compatible between versions so we can migrate workspaces.
