### ISSUE TITLE
Bug with removing star in version 3.0.2

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jdplus-main#84]
[JDemetra+ v 3.0.2]

Even after removing the star, my favorites files doesn't disappear at the restart of a new session of JDemetra+.

Also I have an error at the opening of JDemetra+ with a no entry sign. I don't know if it's related.

![image](https://github.com/jdemetra/jdplus-main/assets/112711017/66a27da8-65a3-4edf-ab81-e31b561cd2f4)

**Comment by charphi** [comment]
There is indeed a bug when removing a star.
However, the error on your screenshot is unrelated.

**Comment by TanguyBarthelemy** [comment]
😧😌

**Comment by charphi** [comment]
Done in ef941f78813345655281db6b7af12d9fb525cdaf
